# -*- coding: utf-8 -*-
"""AGMBiN_batch_Heatmap_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oVVyODfsGQ8ctLjdfeylUZNlwZGOo4rO
"""

import os
import cv2
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from PIL import Image
import torchvision.transforms as transforms
from tqdm import tqdm

# =============================================================================
# 1. ARCHITECTURE (AGMBiN)
# =============================================================================
def drop_path(x, drop_prob: float = 0., training: bool = False):
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)
    random_tensor = keep_prob + torch.rand(shape, dtype=x.dtype, device=x.device)
    random_tensor.floor_()
    output = x.div(keep_prob) * random_tensor
    return output

class ModernManifoldBlock(nn.Module):
    def __init__(self, in_channels, out_channels, stride=1, drop_path_rate=0.1):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels, out_channels, kernel_size=3, stride=stride, padding=1, bias=False)
        self.bn1 = nn.BatchNorm2d(out_channels)
        self.conv2 = nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(out_channels)
        self.act = nn.GELU()
        self.drop_path_rate = drop_path_rate
        self.se = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Conv2d(out_channels, max(1, out_channels // 4), kernel_size=1),
            nn.GELU(),
            nn.Conv2d(max(1, out_channels // 4), out_channels, kernel_size=1),
            nn.Sigmoid()
        )
        self.shortcut = nn.Sequential()
        if stride != 1 or in_channels != out_channels:
            self.shortcut = nn.Sequential(
                nn.Conv2d(in_channels, out_channels, kernel_size=1, stride=stride, bias=False),
                nn.BatchNorm2d(out_channels)
            )

    def forward(self, x):
        identity = self.shortcut(x)
        out = self.bn1(self.act(self.conv1(x)))
        out = self.bn2(self.act(self.conv2(out)))
        out = out * self.se(out)
        out = drop_path(out, self.drop_path_rate, self.training)
        out += identity
        return self.act(out)

class AGMBiN(nn.Module):
    def __init__(self, num_classes=10, base_channels=64, bilinear_dim=128):
        super().__init__()
        self.conv1 = nn.Sequential(
            nn.Conv2d(3, base_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(base_channels),
            nn.GELU()
        )
        self.layer1 = ModernManifoldBlock(base_channels, base_channels * 2, stride=2)
        self.layer2 = ModernManifoldBlock(base_channels * 2, base_channels * 4, stride=2)
        self.layer3 = ModernManifoldBlock(base_channels * 4, base_channels * 8, stride=2)
        self.layer4 = ModernManifoldBlock(base_channels * 8, base_channels * 16, stride=1)
        self.layer5 = ModernManifoldBlock(base_channels * 16, base_channels * 16, stride=2)
        self.attn_pool = nn.Sequential(nn.Conv2d(base_channels * 16, base_channels * 16, kernel_size=1), nn.Sigmoid())
        self.compress = nn.Sequential(nn.Conv2d(base_channels * 16, bilinear_dim, kernel_size=1, bias=False), nn.BatchNorm2d(bilinear_dim), nn.GELU())
        self.fc = nn.Linear(bilinear_dim * bilinear_dim, num_classes)

    def forward(self, x):
        x = self.layer5(self.layer4(self.layer3(self.layer2(self.layer1(self.conv1(x))))))
        x = x * self.attn_pool(x)
        x = self.compress(x)
        B, C, H, W = x.size()
        with torch.amp.autocast('cuda', enabled=False):
            x_flat = x.float().view(B, C, H * W)
            x_flat = torch.clamp(x_flat, min=-100.0, max=100.0)
            bilinear = torch.bmm(x_flat, x_flat.transpose(1, 2)) / (H * W)
            bilinear = bilinear.view(B, C * C)
            bilinear = torch.sign(bilinear) * torch.sqrt(torch.abs(bilinear) + 1e-12)
            bilinear = F.normalize(bilinear, p=2, dim=1)
            logits = self.fc(bilinear)
        return logits


# =============================================================================
# 2. HEATMAP GENERATION & BATCH PROCESSING
# =============================================================================
def save_AGMBiN_heatmap(model, image_path, output_path, device):
    """Generates the attention overlay for a single image and saves it directly to disk."""
    model.eval()

    # Load and resize original image
    original_pil = Image.open(image_path).convert('RGB')
    original_resized = original_pil.resize((224, 224))
    original_np = np.array(original_resized)

    normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    transform = transforms.Compose([transforms.Resize((224, 224)), transforms.ToTensor(), normalize])
    input_tensor = transform(original_pil).unsqueeze(0).to(device)

    # Attach forward hook to the Attention Gate
    attention_map = None
    def hook_fn(module, input, output):
        nonlocal attention_map
        attention_map = output.detach().cpu()

    base_model = model._orig_mod if hasattr(model, '_orig_mod') else model
    hook_handle = base_model.attn_pool.register_forward_hook(hook_fn)

    # Forward pass
    with torch.no_grad():
        with torch.amp.autocast('cuda'):
            model(input_tensor)

    hook_handle.remove()

    # Process heatmap
    heatmap = attention_map.float().mean(dim=1).squeeze().numpy()
    heatmap = np.maximum(heatmap, 0)
    heatmap = (heatmap - np.min(heatmap)) / (np.max(heatmap) - np.min(heatmap) + 1e-8)

    heatmap_resized = cv2.resize(heatmap, (224, 224))
    heatmap_colored = cv2.applyColorMap(np.uint8(255 * heatmap_resized), cv2.COLORMAP_JET)
    heatmap_colored = cv2.cvtColor(heatmap_colored, cv2.COLOR_BGR2RGB)

    # Create overlay
    overlay = cv2.addWeighted(original_np, 0.6, heatmap_colored, 0.4, 0)

    # Convert from RGB back to BGR for OpenCV saving
    overlay_bgr = cv2.cvtColor(overlay, cv2.COLOR_RGB2BGR)
    cv2.imwrite(output_path, overlay_bgr)


def heatmaps_batch_process(source_dir, heatmap_dir, model, device, suffix):
    """Iterates through a folder of images and saves the heatmaps using the provided model."""
    os.makedirs(heatmap_dir, exist_ok=True)

    valid_extensions = ('.png', '.jpg', '.jpeg', '.bmp')
    image_files = [f for f in os.listdir(source_dir) if f.lower().endswith(valid_extensions)]

    print(f"Processing {len(image_files)} images from '{source_dir}' -> '{heatmap_dir}'")

    for file_name in tqdm(image_files, desc=f"Generating {suffix} Heatmaps"):
        image_path = os.path.join(source_dir, file_name)

        name_without_ext = os.path.splitext(file_name)[0]
        output_file_name = f"{name_without_ext}_{suffix}.jpg"
        output_path = os.path.join(heatmap_dir, output_file_name)

        save_AGMBiN_heatmap(model, image_path, output_path, device)


# =============================================================================
# 3. UTILITIES & MAIN EXECUTION
# =============================================================================
def load_robust_checkpoint(model, checkpoint_path, device):
    """Loads a checkpoint, handles dictionary wrappers, and filters shape mismatches."""
    ckpt = torch.load(checkpoint_path, map_location=device)

    # 1. Extract the actual weights (handles standard checkpoints vs raw weights)
    state_dict = ckpt.get('state_dict', ckpt.get('model', ckpt))

    # 2. Filter out keys with shape mismatches (e.g., the 1000-class vs 200-class fc layer)
    model_state = model.state_dict()
    filtered_state_dict = {
        k: v for k, v in state_dict.items()
        if k in model_state and v.shape == model_state[k].shape
    }

    # 3. Load the filtered weights
    model.load_state_dict(filtered_state_dict, strict=False)
    return model

if __name__ == '__main__':
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    # --- Base Directory Paths ---
    model_dir = '/content/drive/MyDrive/Results/AGMBiN/Model_Weights/'
    base_source_dir = '/content/drive/MyDrive/Results/AGMBiN/Data/FGVC_Data/'
    base_heatmap_dir = '/content/drive/MyDrive/Results/AGMBiN/Heatmaps/'

    # Shared base model for "Without Finetuning"
    model_weight_wo_ft = os.path.join(model_dir, 'model_AGMBiN_IN1K_150e.pth')

    # --- Configuration for all 7 Datasets ---
    datasets_config = [
        {'data_folder': 'cub_200',        'hm_folder': 'CUB_200',         'weight': 'ft_model_AGMBiN_CUB.pth',             'num_classes': 200},
        {'data_folder': 'fgvc_aircraft',  'hm_folder': 'FGVC_Aircraft',   'weight': 'ft_model_AGMBiN_FGVC_Aircraft.pth',   'num_classes': 102},
        {'data_folder': 'food_101',       'hm_folder': 'Food_101',        'weight': 'ft_model_AGMBiN_Food_101.pth',        'num_classes': 101},
        {'data_folder': 'oxford_flowers', 'hm_folder': 'Oxford_Flowers',  'weight': 'ft_model_AGMBiN_Oxford_Flowers.pth',  'num_classes': 102},
        {'data_folder': 'oxford_pet',     'hm_folder': 'Oxford_IIIT_Pet', 'weight': 'ft_model_AGMBiN_Oxford_IIIT_Pet.pth', 'num_classes': 37},
        {'data_folder': 'stanford_cars',  'hm_folder': 'Stanford_Cars',   'weight': 'ft_model_AGMBiN_Stanford_Cars.pth',   'num_classes': 196},
        {'data_folder': 'stanford_dogs',  'hm_folder': 'Stanford_Dogs',   'weight': 'ft_model_AGMBiN_Stanford_Dogs.pth',   'num_classes': 120}
    ]

    # --- Iterating over all Datasets ---
    for config in datasets_config:
        print("\n" + "="*60)
        print(f"PROCESSING DATASET: {config['hm_folder'].upper()}")
        print("="*60)

        # Dynamic Paths
        source_dir = os.path.join(base_source_dir, config['data_folder'])
        heatmap_dir_wo_ft = os.path.join(base_heatmap_dir, config['hm_folder'], 'Without_Finetuning')
        heatmap_dir_with_ft = os.path.join(base_heatmap_dir, config['hm_folder'], 'With_Finetuning')
        model_weight_w_ft = os.path.join(model_dir, config['weight'])
        num_classes = config['num_classes']

        # ---------------------------------------------------------
        # 1. Process WITHOUT Finetune
        # ---------------------------------------------------------
        if os.path.exists(model_weight_wo_ft):
            print(f"\n---> [1/2] Generating 'Without Finetuning' Heatmaps")
            try:
                model_wo_ft = AGMBiN(num_classes=num_classes).to(device)
                model_wo_ft = load_robust_checkpoint(model_wo_ft, model_weight_wo_ft, device)

                heatmaps_batch_process(
                    source_dir=source_dir,
                    heatmap_dir=heatmap_dir_wo_ft,
                    model=model_wo_ft,
                    device=device,
                    suffix='AGMBiN_wo_ft'
                )
            except Exception as e:
                print(f"❌ ERROR loading {model_weight_wo_ft}: {e}")
                print("Skipping 'Without Finetuning' for this dataset...")
        else:
            print(f"⚠️ Warning: Base IN1K weight file not found at {model_weight_wo_ft}. Skipping.")

        # ---------------------------------------------------------
        # 2. Process WITH Finetune
        # ---------------------------------------------------------
        if os.path.exists(model_weight_w_ft):
            print(f"\n---> [2/2] Generating 'With Finetuning' Heatmaps")
            try:
                model_w_ft = AGMBiN(num_classes=num_classes).to(device)
                model_w_ft = load_robust_checkpoint(model_w_ft, model_weight_w_ft, device)

                heatmaps_batch_process(
                    source_dir=source_dir,
                    heatmap_dir=heatmap_dir_with_ft,
                    model=model_w_ft,
                    device=device,
                    suffix='AGMBiN_w_ft'
                )
            except Exception as e:
                print(f"❌ ERROR loading {model_weight_w_ft}: {e}")
                print("Skipping 'With Finetuning' for this dataset due to corrupted/invalid checkpoint...")
        else:
            print(f"⚠️ Warning: Finetuned weight file not found at {model_weight_w_ft}. Skipping.")

    print("\n" + "="*60)
    print("ALL BATCH PROCESSING SEQUENCES COMPLETED!")
    print("="*60)